// The page left at an old address once Overlap moves: it sends every link on to
// the same path at the new address, and hands over what this browser remembered
// there (localStorage "overlap.*": polls you made or answered, drafts, language)
// in the new link's #fragment, which never reaches any server. The new address
// merges it in (public/js/lib/moved.js, which must list the old address in
// MOVED_FROM: build-pages.mjs --moved-from).
//   node scripts/build-moved.mjs --to https://overlap.runtianwu.com --out <dir> [--domain overlap.runtian.uk]
// Other files already in the output directory (the old app's scripts and styles)
// are left alone, so a copy of the old page cached before the move still loads.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

/** The files of the page, by path. `to` is the new address's origin. */
export function movedFiles(to) {
  const origin = new URL(to).origin;
  const host = new URL(to).host;
  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self'; base-uri 'none'; form-action 'none'">
  <meta name="referrer" content="origin">
  <meta name="color-scheme" content="light dark">
  <meta name="robots" content="noindex">
  <title>Overlap has moved</title>
  <link rel="canonical" href="${origin}/">
  <script src="/moved.js" defer></script>
  <noscript><meta http-equiv="refresh" content="0; url=${origin}/"></noscript>
</head>
<body>
  <p>Overlap has moved to <a id="to" href="${origin}/">${host}</a>.</p>
</body>
</html>
`;
  // The referrer policy above sends just this address's origin with the move,
  // which is how the new address knows the hand-over came from here.
  const js = `// Generated by scripts/build-moved.mjs
(async () => {
  const TO = ${JSON.stringify(origin)};
  const remembered = {};
  try {
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && key.startsWith('overlap.')) remembered[key] = localStorage.getItem(key);
    }
  } catch { /* storage blocked: move without it */ }
  let hash = location.hash.slice(1).replace(/(?:^|&)moved=[^&]*/g, '').replace(/^&/, '');
  if (Object.keys(remembered).length) {
    try {
      const moved = await encode(JSON.stringify(remembered));
      hash = hash ? hash + '&moved=' + moved : 'moved=' + moved;
    } catch { /* move without it */ }
  }
  const target = TO + location.pathname + location.search + (hash ? '#' + hash : '');
  const link = document.getElementById('to');
  if (link) link.href = target;
  location.replace(target);
})();

async function encode(text) {
  let bytes = new TextEncoder().encode(text);
  let tag = 'j';
  if (typeof CompressionStream === 'function') {
    const stream = new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate-raw'));
    bytes = new Uint8Array(await new Response(stream).arrayBuffer());
    tag = 'z';
  }
  let bin = '';
  for (let i = 0; i < bytes.length; i += 0x8000) bin += String.fromCharCode.apply(null, bytes.subarray(i, i + 0x8000));
  return tag + btoa(bin).replace(/\\+/g, '-').replace(/\\//g, '_').replace(/=+$/, '');
}
`;
  return {
    'index.html': html,
    // Every other path (poll links like /p/abc123) is answered with 404.html on GitHub Pages.
    '404.html': html,
    'about/index.html': html,
    'privacy/index.html': html,
    'moved.js': js,
  };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const args = Object.fromEntries(process.argv.slice(2).reduce((acc, a, i, all) => (a.startsWith('--') ? [...acc, [a.slice(2), all[i + 1]]] : acc), []));
  if (!args.to || !args.out) {
    console.error('Usage: node scripts/build-moved.mjs --to <https://new-address> --out <dir> [--domain overlap.runtian.uk]');
    process.exit(1);
  }
  const out = resolve(args.out);
  mkdirSync(out, { recursive: true });
  for (const [path, text] of Object.entries(movedFiles(args.to))) {
    mkdirSync(dirname(join(out, path)), { recursive: true });
    writeFileSync(join(out, path), text);
  }
  writeFileSync(join(out, '.nojekyll'), '');
  if (args.domain) writeFileSync(join(out, 'CNAME'), `${args.domain}\n`);
  if (!existsSync(join(out, 'README.md'))) writeFileSync(join(out, 'README.md'), '# Overlap (old address)\n');
  console.log(`Built ${out} (moves to ${new URL(args.to).origin})`);
}
