// Build the static site for GitHub Pages, talking to the API at --api.
//   node scripts/build-pages.mjs --api https://overlap-api.example.workers.dev --out <dir> [--domain overlap.runtianwu.com]
//     [--moved-from https://overlap.runtian.uk]  an old address whose remembered polls are handed over (scripts/build-moved.mjs)
// The output directory is emptied first, except .git, CNAME and README.md
// (losing CNAME would drop the custom domain; see docs/runtian-uk-website.md).

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const args = Object.fromEntries(process.argv.slice(2).reduce((acc, a, i, all) => (a.startsWith('--') ? [...acc, [a.slice(2), all[i + 1]]] : acc), []));
if (!args.api || !args.out) {
  console.error('Usage: node scripts/build-pages.mjs --api <https://worker-url> --out <dir> [--domain overlap.runtianwu.com] [--moved-from <https://old-address>]');
  process.exit(1);
}
const api = new URL(args.api).origin;
const out = resolve(args.out);
const PRESERVE = new Set(['.git', 'CNAME', 'README.md']);

mkdirSync(out, { recursive: true });
for (const name of readdirSync(out)) if (!PRESERVE.has(name)) rmSync(join(out, name), { recursive: true, force: true });

cpSync(join(ROOT, 'public'), out, { recursive: true });
cpSync(join(ROOT, 'shared'), join(out, 'shared'), { recursive: true });
const movedFrom = args['moved-from'] ? args['moved-from'].split(',').map((u) => new URL(u.trim()).origin) : [];
writeFileSync(join(out, 'js/config.js'), `// Generated by scripts/build-pages.mjs\nexport const API_BASE = ${JSON.stringify(api)};\nexport const MOVED_FROM = ${JSON.stringify(movedFrom)};\n`);

// GitHub Pages can't send headers, so the security policy goes in meta tags.
const csp = [
  "default-src 'self'", "script-src 'self'", "style-src 'self'", "img-src 'self' data:", "font-src 'self'",
  `connect-src 'self' ${api}`, "object-src 'none'", "base-uri 'none'", "form-action 'self'",
].join('; ');
const html = readFileSync(join(out, 'index.html'), 'utf8').replace('<meta charset="utf-8">',
  `<meta charset="utf-8">\n  <meta http-equiv="Content-Security-Policy" content="${csp}">\n  <meta name="referrer" content="no-referrer">`);
writeFileSync(join(out, 'index.html'), html);
// Poll links like /p/abc123 aren't files; GitHub Pages answers them with 404.html,
// which is the same app shell, and the app routes from the address.
writeFileSync(join(out, '404.html'), html);
// Fixed pages get real files so they answer 200 rather than via the 404 fallback.
for (const page of ['about', 'privacy']) {
  mkdirSync(join(out, page), { recursive: true });
  writeFileSync(join(out, page, 'index.html'), html);
}
writeFileSync(join(out, '.nojekyll'), '');
if (args.domain) writeFileSync(join(out, 'CNAME'), `${args.domain}\n`);
if (!existsSync(join(out, 'README.md'))) {
  writeFileSync(join(out, 'README.md'), `# Overlap (published site)\n\nBuilt output of Overlap for GitHub Pages. Do not edit by hand: rebuild with\n\`node scripts/build-pages.mjs\` from the Overlap source folder. The API runs on Cloudflare Workers.\n`);
}
console.log(`Built ${out} (API ${api})`);
