#!/usr/bin/env node
// node scripts/i18n.mjs merge            build shared/i18n/en.js from shared/i18n/en/*.js
// node scripts/i18n.mjs assemble <code>  build shared/i18n/<code>.js from shared/i18n/<code>/*.js
// node scripts/i18n.mjs check [<code>]   every language (or one) has every key, the same
//                                        placeholders, and the right plural forms

import { readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { LANGUAGES } from '../shared/i18n/languages.js';

const DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'shared', 'i18n');
const load = async (file) => (await import(`${pathToFileURL(file).href}?t=${Date.now()}`)).default;

async function combine(code) {
  const merged = {};
  for (const file of readdirSync(join(DIR, code)).filter((f) => f.endsWith('.js')).sort()) {
    const part = await load(join(DIR, code, file));
    for (const [k, v] of Object.entries(part)) {
      if (k in merged) throw new Error(`Duplicate key ${k} (in ${code}/${file})`);
      merged[k] = v;
    }
  }
  return Object.fromEntries(Object.entries(merged).sort(([a], [b]) => a.localeCompare(b)));
}

/** A translation from its parts (shared/i18n/<code>/*.js, mirroring en/). */
export async function assemble(code) {
  const sorted = await combine(code);
  writeFileSync(join(DIR, `${code}.js`), `// Generated by \`node scripts/i18n.mjs assemble ${code}\` from shared/i18n/${code}/*.js. Edit those, not this.\nexport default ${JSON.stringify(sorted, null, 2)};\n`);
  return Object.keys(sorted).length;
}

export async function merge() {
  const sorted = await combine('en');
  writeFileSync(join(DIR, 'en.js'), `// Generated by \`npm run i18n:merge\` from shared/i18n/en/*.js. Edit those, not this.\nexport default ${JSON.stringify(sorted, null, 2)};\n`);
  // Every catalog that exists, imported statically, for the server (emails).
  // Static imports let the Cloudflare Worker bundle them.
  const present = LANGUAGES.map((l) => l.code).filter((c) => readdirSync(DIR).includes(`${c}.js`));
  const ident = (c) => c.replace(/-/g, '_');
  writeFileSync(join(DIR, 'catalogs.js'), `// Generated by \`npm run i18n:merge\`. The server's copy of every language (for emails).\n${present.map((c) => `import ${ident(c)} from './${c}.js';`).join('\n')}\n\nexport default { ${present.map((c) => `'${c}': ${ident(c)}`).join(', ')} };\n`);
  return Object.keys(sorted).length;
}

const placeholders = (text) => [...String(text).matchAll(/\{(\w+)\}/g)].map((m) => m[1]).sort().join(',');
const variants = (v) => (typeof v === 'object' ? Object.values(v) : [v]);

export async function check(only = null) {
  const en = await load(join(DIR, 'en.js'));
  const problems = [];
  for (const { code } of LANGUAGES) {
    if (code === 'en' || (only && code !== only)) continue;
    let cat;
    try { cat = await load(join(DIR, `${code}.js`)); } catch (e) { problems.push(`${code}: missing file (${e.message})`); continue; }
    const want = new Intl.PluralRules(code).resolvedOptions().pluralCategories;
    for (const [key, source] of Object.entries(en)) {
      if (!(key in cat)) { problems.push(`${code}: missing ${key}`); continue; }
      const value = cat[key];
      const srcPh = placeholders(variants(source).join(' '));
      if (typeof source === 'object') {
        if (typeof value !== 'object') { problems.push(`${code}: ${key} should have plural forms`); continue; }
        for (const c of want) if (!(c in value)) problems.push(`${code}: ${key} lacks plural form "${c}"`);
        for (const c of Object.keys(value)) if (!want.includes(c)) problems.push(`${code}: ${key} has plural form "${c}", which ${code} doesn't use`);
      } else if (typeof value !== 'string') {
        problems.push(`${code}: ${key} should be text`);
        continue;
      }
      for (const v of variants(value)) {
        if (!String(v).trim()) problems.push(`${code}: ${key} is empty`);
        const extra = placeholders(v).split(',').filter((p) => p && !srcPh.split(',').includes(p));
        if (extra.length) problems.push(`${code}: ${key} has unknown placeholder(s) ${extra.join(', ')}`);
      }
      // Every English placeholder appears in at least one form (a "one" form may spell out the number).
      const all = placeholders(variants(value).join(' ')).split(',');
      for (const p of srcPh.split(',').filter(Boolean)) if (!all.includes(p) && p !== 'count') problems.push(`${code}: ${key} lost {${p}}`);
    }
    for (const key of Object.keys(cat)) if (!(key in en)) problems.push(`${code}: unknown key ${key}`);
  }
  return problems;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const cmd = process.argv[2];
  if (cmd === 'merge') console.log(`en.js: ${await merge()} keys`);
  else if (cmd === 'assemble') console.log(`${process.argv[3]}.js: ${await assemble(process.argv[3])} keys`);
  else if (cmd === 'check') {
    const problems = await check(process.argv[3] || null);
    if (problems.length) { console.error(problems.slice(0, 200).join('\n')); console.error(`${problems.length} problem(s)`); process.exit(1); }
    console.log('All languages complete.');
  } else { console.error('Usage: node scripts/i18n.mjs merge | assemble <code> | check [<code>]'); process.exit(2); }
}
